### ISSUE TITLE
some types of pressure plates are not detecting

### ISSUE THREAD

**Issue by homerek111** [Despical/KOTL#21] opened 2024-04-15 22:26 UTC
idk why it happens but for example gold and iron pressure plates work fine all the time but for example crimson_pressure_plate or dark_oak_pressure_plate or polished_blackstone_pressure_plate do not work - they aren't detecting players

gold and iron plates are working all good - many others do not...

i  tried reloading / restarting etc.

**Comment by Despical** [comment] 2024-04-16 07:44
What is your server version and server software? I have just tested and all of them works fine both in Minecraft 1.20.1 and 1.20.4.

There also some differents for each plate, for example `Gold and iron pressure plates give signal strength based off how many entities are on them, gold requires more entities than iron for a high strength signal. Wooden pressure plates detect all entities, stone pressure plates only detect mobs or players`.

**Comment by homerek111** [comment] 2024-04-16 12:16
> What is your server version and server software? I have just tested and all of them works fine both in Minecraft 1.20.1 and 1.20.4.

Version: `This server is running Paper version git-Paper-477 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1207162) You are 7 version(s) behind`
Software: Java 17

> There also some differents for each plate, for example Gold and iron pressure plates give signal strength based off how many entities are on them, gold requires more entities than iron for a high strength signal. Wooden pressure plates detect all entities, stone pressure plates only detect mobs or players.

Whatever type of plate would it be all these should trigger player... As i said on my server ONLY light_weighted_pressure_plate (golden one) and heave_weighted_pressure_plate (iron one) work. Using other types of plates makes plugin not detecting players and not giving them king status...

**Comment by Despical** [comment] 2024-04-17 16:46
Is that issue solved?

**Comment by homerek111** [comment] 2024-04-17 16:51
> Is that issue solved?

Oh I turned off my pc and didn’t check that after changing rewards interval (but I believe this issue might still be happening cuz I don’t see connection with that config option here)

I will test that in +/- 1h and let you know

**Comment by homerek111** [comment] 2024-04-17 18:12
> Is that issue solved?

@Despical i checked every single plate and still only light_weighted_pressure_plate (golden one) and heave_weighted_pressure_plate (iron one) work. All other types does not trigger king change
![obraz](https://github.com/Despical/KOTL/assets/93496464/6ac24dea-bf48-4a26-a215-95420b720382)

**Comment by Despical** [comment] 2024-04-17 18:57
@homerek111 Here is a [test video](https://www.youtube.com/watch?v=AwqV-U7rYR0), all config files for Paper and KOTL are at their default settings.

**Comment by homerek111** [comment] 2024-04-17 19:18
> @homerek111 Here is a [test video](https://www.youtube.com/watch?v=AwqV-U7rYR0), all config files for Paper and KOTL are at their default settings.

it must be caused with some specific configuration that I use. I will test it using default settings and then change one by one to my current settings to find out when it breaks

**Comment by Despical** [comment] 2024-04-17 19:47
> > @homerek111 Here is a [test video](https://www.youtube.com/watch?v=AwqV-U7rYR0), all config files for Paper and KOTL are at their default settings.
> 
> it must be caused with some specific configuration that I use. I will test it using default settings and then change one by one to my current settings to find out when it breaks

Leaving the issue opened for now.

**Comment by homerek111** [comment] 2024-04-17 22:22
> > @homerek111 Here is a [test video](https://www.youtube.com/watch?v=AwqV-U7rYR0), all config files for Paper and KOTL are at their default settings.
> 
> it must be caused with some specific configuration that I use. I will test it using default settings and then change one by one to my current settings to find out when it breaks

@Despical it must be connected with worldguard - but i can't find flag to fix it...
Results of my tests (with all default configuration):

1. I created preassure plate where are 2 worldguard regions and 1 `__global__` region:
Inside this 3 regions ONLY golden and iron pressure plates work
a) first region `grota_plytka`
![obraz](https://github.com/Despical/KOTL/assets/93496464/7d269210-5aae-46d2-8856-94599ae33677)
b) second region `grota`
![obraz](https://github.com/Despical/KOTL/assets/93496464/39958aeb-b806-48cc-9730-05e2a1c53612)
c) region ``__global__``
![obraz](https://github.com/Despical/KOTL/assets/93496464/d318865c-b8db-4a2b-8f51-b8e831f62093)

2. I created preassure plate where there is only 1 `__global__` region:
Inside this __global__ region ALL pressure plates work
a) region ``__global__``
![obraz](https://github.com/Despical/KOTL/assets/93496464/d318865c-b8db-4a2b-8f51-b8e831f62093)


There must be some worldguard limitation that blocks other plates than golden and iron from triggering new king... Maybe it's something that you should override in your plugin
What's weired usage of all plates is enabled with `use: allow` and `interact: allow` flags + I AM OPPED so worldguard flags shouldnt block me from anything...

**Comment by Despical** [comment] 2024-04-18 14:04
There are priorities for the regions, I think you have to give it a higher priority to make pressure plates work.

**Comment by homerek111** [comment] 2024-04-18 14:56
> There are priorities for the regions, I think you have to give it a higher priority to make pressure plates work.

Priorities are done correctly - golden and iron plates work properly + region flags shouldn’t block OPped player from using plates 

I don’t think there is any difference between pressure plates types according to worldguard flags…

**Comment by homerek111** [comment] 2024-04-18 17:33
@Despical I made more tests and I realised that worldguard is not the one that makes plates not work... (I was wrong before)
In my configuration I use small arena regions 1x1 blocks (only for pressure plate) 

I realised that in 1x1 region only golden and iron pressure plate work properly - other plates need bigger arena regions (when i created a bigger arena all plates started working fine)
Idk if it's a plugin's bug or some minecraft mechanics make it necessary to use bigger arena regions to use other plates...

Personally I will just use these 2 types that work fine with 1x1 arena but maybe it's something that can be fixed from plugin's side

**Comment by Despical** [comment] 2024-04-18 19:38
If plugin works properly without the World Guard then the issue is related to World Guard plugin.

**Comment by homerek111** [comment] 2024-04-18 19:41
> If plugin works properly without the World Guard then the issue is related to World Guard plugin.

@Despical After todays tests i realised it's not related to WorldGuard. 
It's related with KOTL arena's region size (when it's 1x1 other plates than golden/iron don't work) - when i said it was about worldguard I was wrong

**Comment by Despical** [comment] 2024-04-18 20:16
Arenas can not be 1x1.

**Comment by homerek111** [comment] 2024-04-18 20:44
> Arenas can not be 1x1.

It is possible and it works well
https://pastebin.com/84yTb2UF

**Comment by Despical** [comment] 2024-04-18 20:52
Yes, it may work but game is designed for bigger areas. It shouldn't be done that way.

**Comment by homerek111** [comment] 2024-04-18 21:00
> Yes, it may work but game is designed for bigger areas. It shouldn't be done that way.

I know - i use the plugin in kinda weired way for my server's needs 

Anyways... If you would like to close this ticket I dont have problem with pressure plates anymore as i use the ones that work only

I found some issues in #20 (described you everything there)

**Comment by Despical** [comment] 2024-04-18 21:17
Okay, if you experience the same issue on a bigger scaled arena you should open another issue because. Closing this one for now.

**Closed as completed by Despical** 2024-04-18 21:17 UTC
